---
title: "First Knit"
author: "Jordan Barnes"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended High School at Desert Christian High in Lancaster. I went to that school since kindergarten, honestly I wasn't very fond of the school itself but my friends and my senior class definitely made my high school years memorable. I graduated in the class of 2023. English and Math are probably my best subjects, I’d say I am rather fluent in writing and calculating numbers doesn't come across as a challenge to me. I did best in every subject other than science, science based classes are harder for me because I get bored really easily throughout all sub categories amongst science.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a windows desktop and a macbook air at home. I have my own pc at home and know pretty much everything simple when it comes to computer technology, I am not a complete geek but I did build my own pc and I understand what specs are good and what works best together, I’d rate my computer knowledge about an 8. My internet at home is stable, I used to have lots of internet problems and lag a lot but as of lately it has been great.   
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
At baseball all my boys call me Barnesy, it’s a nickname originating after my last name, but in school I’d prefer to just be called Jordan.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
My goal in all of life is to be successful and happy, but I do have short term goals. Right now my biggest goal is to have 1.5 million dollars under my name by the age of 25. I have my own ecommerce businesses and I am invested heavily while also having some other jobs. It's great money for a 19 year old kid but I want to eventually be truly financially free and obtain the skill of making generational wealth. Right now I am studying for a Business Admin degree, that is what interests me the most, being my own boss and understanding all endeavors of the business world.  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have never gone to foreign countries, my family has always been too busy to travel so I rarely traveled when I was younger. I’ve only been to California, Nevada, Arizona, and Hawaii. I really do want to travel with my friends to New York, Paris, Japan, Canada, and Germany. I have never been in the military, I have thought about joining but I wouldn’t want to join as an E2 or E3, rather do 4 years of schooling and enlist as an officer in order to become a pilot. I would join the Air Force simply because the only thing that interests me in the military is flying planes and potentially becoming a fighter pilot  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




